	var m = [
	'Nó Hình Gì?'
	,'Để hiểu học trò hơn, cô giáo bảo học sinh vẽ vào một tờ giấy mơ ước mai sau của mình.\nKhi cô xem, có em vẽ hình máy bay tỏ ý muốn làm phi công, em thì vẽ ống nghe muốn làm bác sĩ…\nRiêng Natasha để tờ giấy trắng nguyên, cô hỏi:\n-Chẳng lẽ lớn lên em không muốn làm gì cả sao?\n Natasha băn khoăn đáp:\n- Lớn lên em sẽ lấy chồng, nhưng chẳng biết nó hình gì?'
	,'Bác Sĩ Vô Va'
	,'Lớn lên Vova đi làm bác sĩ, một hôm găp một bệnh nhân rất khó tính và không ai dám làm việc mà anh ta yêu cầu.\nVova gặp và gọi anh ta đến bệnh viện,anh chàng bước vào bệnh viện, đòi giải phẫu cái…ấy của anh ta cho dài đụng đất và trả trước một khoản tiền lớn.\nSau khi đuợc chụp thuốc mê, anh ta không còn biết gì.\nHôm sau tỉnh lại, nhìn thấy đôi chân của mình đã bị cắt cụt tới tận bẹn, anh ta cự nự bác sĩ.\nBác sĩ Vova từ tốn trả lời:\n “Anh muốn cái …ấy dài đụng đất mà, anh xem xem nó có đụng đất chưa?“'
	,'Ở Giữa Hai Chân'
	,'Một hôm cô giáo bảo Vôva bê hộ 1 tập vở chính tả đi từ ban giám hiệu lên phòng học để trả các bạn, Vô va đi sau nhưng vì vướng tập vở không nhìn đươc phía trước cho nên nó cứ đâm sầm phải cô giáo mấy lần, đến chỗ gầm cầu thang thì đứng lại và nó cứ vặn vẹo cả người. Cô giáo thấy vậy liền hỏi.\n-Vôva em sao vậy? Cô giúp được không?\n-Em bị ngứa ạ!\n-Em ngứa ở chỗ nào cô gãi giúp cho\n-Em…\n-Sao vậy cứ nói đi….\n-Em bị ngứa ở giữa…giữa…2 chân ạ.\nCô giáo đỏ mặt và mắng Vova láo. Vova nghĩ đầu gối mình có cái gì nhỉ?'
	,'Vô va Nghĩ Bậy'
	,'Vova đi chơi với Nana. Vova chọn 1 cái ghế đá ngồi xuống, khổ đây là lần đầu tiên nên Vova lúng túng lắm không biết nói gì cả. Nghĩ mãi Vova đánh liều nói 1 câu :\n- Nana, đằng ấy đang nghĩ gì thế?\n-Tớ nghĩ giống đằng ấy !!!!!\nNana trả lời bẽn lẽn. Bỗng Vova cười ha hả:\n-Khiếp sao đằng ấy bậy thế!!!!!!!'
	,'Vô Va Và Câu Hỏi Dành Cho Cô Giáo'
	,'Trong giờ học, cô giáo muốn phát triển trí tưởng tượng và khả năng cảm nhận của học sinh nhỏ tuổi. Cô đưa ra mấy câu hỏi như sau:\n- Các con hãy nghĩ xem, cái gì màu xám và rất là cứng?\n- Bê tông ạ!\nCô giáo:\n- Giỏi quá. Nhưng mà nó còn có thể là nhựa đường nữa, thế còn cái gì màu vàng và ở trên cánh đồng?\n- Con bò ạ!\n- Đúng rồi! Nhưng còn có thể là đống rơm nữa-Vova lẩm bẩm, từ phía cuối lớp.\nCô giáo:\n- Em đứng lên ngay.\nVova:\n- Thế em hỏi một câu được không?\n Cô giáo thận trọng:\n- Em thử nói đi!\n- Thế cái gì trước khi cho vào miệng thì nó cứng, thẳng và khô ráo, còn sau khi ra khỏi miệng thì nó mềm nhũn, cong queo và ướt nhem?\n Cô giáo đứng phắt dậy, mặt đỏ bừng, tiến thẳng đến tát rất kêu vào mặt Vova.Vova xoa xoa má:\n- Đúng rồi! Nhưng nó còn có thể là kẹo cao su nữa!'
	,'Vô va Và Thầy Giáo Dự Giờ'
	,'Tiết tiếng Anh hôm nay lớp học của Vova có một số thầy giáo đến dự giờ.\nCô giáo và các bạn học sinh đã chuẩn bị tất cả tình huống có thể xảy ra để buổi học diễn ra được “an toàn”.\nNửa tiếng trôi qua êm đẹp, còn 15 phút nữa là hết giờ, cô giáo liền hỏi học sinh câu hỏi cuối cùng:\n- Bây giờ cô sẽ viết một câu tiếng Anh lên bảng, các em hãy cố gắng dịch nó ra tiếng Tây Ban Nha nhé!\n Cô giáo đang viết dở câu thì viên phấn bị rơi, cô cúi xuống nhặt và tiếp tục viết cho hết câu.\n-Và bây giờ ai sẽ dịch được câu này?\nVova lập tức giơ tay.Cô giáo thì rất run, nhìn quanh lớp nhưng ngoài Vova ra thì chẳng có ai giơ tay cả. Cô giáo đành chỉ định Vova phát biểu.Vova rất tự tin nói dõng dạc:\n- Giá mà cái váy nó ngắn hơn tí nữa!\nCô giáo đỏ mặt, quát:\n- Cái gì? Em ra ngay khỏi lớp học cho tôi!\nVova thu gom sách vở xong rồi quay lại nhìn thầy giáo dự giờ lẩm bẩm:\n- Đã không biết thì đừng có nhắc!!'
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	]
	/*,'','Vova phải trông em cho bố mẹ đi xuống phố mua sắm, cậu đành phải cho em theo đi câu cá. Tối hôm đó, cậu dằn dỗi với mẹ:- Từ nay con không cho em đi câu nữa đâu. Chỉ mất công, chả được con cá nào!- Ồ! Nó quấy khóc làm cá sợ phải không? Lần sau em sẽ quen, thôi không khóc nữa.- Không phải thế! Em đã ăn hết mồi câu của con.'
	,'Vô Va Và Thầy Giáo Dự Giờ','Trong giờ học cô giáo đang giảng bài về con cò và con gấu. Để mở đầu cô giáo hỏi học sinh:- cô hỏi cả lớp con gì biết bay nè!Mọi cánh tay đều giơ lên trong đó có vova là giơ cao nhất và chưa đợi cô mời cu cậu đã đứng phắt lên trả lời :-Thưa cô là con chim ạ .Không đúng ý cô, cô hơi bực:-Em nghĩ vậy nhưng cô nghĩ khác, cô nghĩ đó là con cò .-Vậy các em cho cô biết con gì sống trong rừng có lông lá đầy mình ?Lại la vo-va:-Thưa cô đó là con khỉ ạ!Lần này thì cô giáo bực thiệt rồi:-Em nghĩ vậy nhưng cô nghĩ là con gấu. Các em còn muốn hỏi gì nữa không ?Lại cu vova:-Thưa cô, vậy em đố cô chứ cái gì dài khoảng 10 cm, thụt ra thụt vào mà phụ nữ rất thích?Cô giáo nghe xong đỏ cả mặt,liền mắng:-Vova đố bậy cô đuổi em ra khỏi lớp bây giờ.-Thưa cô cô nghĩ như thế nhưng theo em đó là……cây son môi!'
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	,'',''
	*/
	
	


